apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: testing
  labels:
    app: flask-app
spec:
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80        # External port for the service
      targetPort: 5000 # Port where the Flask app is running
  type: LoadBalancer

